### PR TITLE
Support `--overwrite` options

### PR DESCRIPTION
**Pull request by tengyifei**
Fixes https://github.com/maxogden/electron-packager/issues/39

Problem does not appear on Windows.

Tested on Mac. Would appreciate anyone to try this on linux.

### CODE REVIEW

**Comment by jden** [comment]
@tengyifei could you please rebase and squash into one commit?

**Comment by tengyifei** [comment]
Done.

**Comment by tengyifei** [comment]
Any update on when this could get merged?

**Comment by kfranqueiro** [comment]
It should probably have been noted that this PR never touched the windows code path...

I will have this resolved for all 3 centrally in `index.js` on the branch that I PR once I figure out rebasing it.

**Pull request merged**
