### PR TITLE
Pipe optional cache option to electron-download

### PR DESCRIPTION
**Pull request by quicksnap**
Possible PR for #112 but might need some doc changes.

### CODE REVIEW

**Comment by quicksnap** [comment]
Looking at code, probably fine to just add the key--if it's `undefined` it won't affect `electron-download`

**Comment by malept** [comment]
Definitely needs some docs.

**Comment by quicksnap** [comment]
I can add those, but LMK if you'd accept something like this first =)

**Comment by quicksnap** [comment]
Also, for context, I desire this because we'll be rolling a customized electron build, and overriding the cache would make things easier for me.

**Comment by malept** [comment]
Seems reasonable to me. We could use it to speed up the Travis tests, too.

**Comment by quicksnap** [comment]
Cool--I'll write up changes tomorrow.

**Comment by quicksnap** [comment]
Updated PR with documentation and adjustment to the implementation

**Comment by quicksnap** [comment]
Any update? Good to merge? =)

**Pull request merged**
