### PR TITLE
fixes#101 pass --unpack argument to the asar option

### PR DESCRIPTION
**Pull request by krishnaIndia**
fixes#101 Integrated asar options for unpack and snapshot.

`unpack` can be used by passing the flag `--asar_unpack`

Similarly `snapshot` option  can be passed with the flag `--asar_snapshot` 

Example usage,
```
electron-packager . my_app --out=dist --ignore=dist --prune --asar --asar_unpack=*.dylib --platform=darwin --arch=x64 --version=0.30.0 --overwrite
```

Have tested these features [here](https://github.com/krishnaIndia/dns_manager/blob/master/package.json#L21)

### CODE REVIEW

**Comment by maxogden** [comment]
@krishnaIndia looks like there are some style issues with the PR that made travis fail, check https://travis-ci.org/maxogden/electron-packager/builds/77451881 or run `npm test` locally

**Comment by krishnaIndia** [comment]
Cheers @maxogden! I have fixed the style issue

**Comment by malept** [comment]
A few things:

* The rest of the flags are hyphen-delimited, not underscore-delimited (for example, `--asar-unpack`)
* Would it be possible to add tests for this feature?
* The new flags should be documented in `readme.md` and `usage.txt`.

**Comment by krishnaIndia** [comment]
Makes sense @malept. I ll try to make those changes and push again.

**Comment by krishnaIndia** [comment]
Closing this. A new PR is raised for the same https://github.com/maxogden/electron-packager/pull/126

**Pull request closed without merging**
