### PR TITLE
Add option to pass --unpack argument to asar

### LINKED ISSUE #101: Can we pass --unpack argument to the asar option?
I'd like to exclude some node native addons from the output asar file. But I haven't figured out how to pass the --unpack argument to asar option. Does electron-packager support --unpack argument? Please give me some hints. Thanks a lot.

### PR DESCRIPTION
**Pull request by krishnaIndia**
fixes #101 Integrated asar options for unpack and snapshot.

unpack can be used by passing the flag --asar-unpack

This option would enable users to unpack files to `app.asar.unpacked` directory. asar-unpack accepts regex string for referring the files to be unpacked

### CODE REVIEW

**Comment by krishnaIndia** [comment]
asar-unpack usage is added to usage.txt and readme.md

**Comment by malept** [comment]
The commits should be rebased into one commit. Apart from that, I don't have any opinions on this PR (I don't use the asar functionality at the moment). Does any other contributor have comments?

**Comment by maxogden** [comment]
LGTM, gonna merge (I don't mind commit noise :P)

**Comment by malept** [comment]
Personally, I don't mind commit noise either. There are certain other contributors who do :grin:

**Comment by maxogden** [comment]
released as 5.1.0

**Pull request merged**
