### PR TITLE
add windows support - #3

### PR DESCRIPTION
**Pull request by jden**
supports:

- input directory
- name
- asar
- prune
- icon

not implemented:
- protocols
- app-version

### CODE REVIEW

**Comment by maxogden** [comment]
YER A WIZARD HARRY!

**Comment by jden** [comment]
lemme fix the standard style things... 1 sec

**Comment by marwanhilmi** [comment]
I'm working with Electron + Windows and can give this a test run. Thanks @jden!
@maxogden @jden Are you interested in adding installer support as well (ie. creating a Setup.exe)?

**Comment by jden** [comment]
@marwanhilmi see the discussion I raised in #21

**Comment by Ivshti** [comment]
@maxogden can this be merged?

**Comment by maxogden** [comment]
released as 3.4.0

**Comment by maxogden** [comment]
also added @jden as a collaborator. this means you can npm publish and manage issues/merge PRs (use your best judgment)

**Comment by maxogden** [comment]
@jden I just pushed a pretty major change (4.0.0). Would you mind making sure I didn't break your windows support? I verified it can build a windows app still but I dunno if its a valid app or not

**Comment by jden** [comment]
:+1: works for me on win32-x64 building on Windows 8.1 x64.

**Pull request merged**
