### PR TITLE
Added --sign to mac

### PR DESCRIPTION
**Pull request by jenslind**
It's a start. Starting to get ugly with all them callbacks though. :)

https://github.com/maxogden/electron-packager/issues/16

### CODE REVIEW

**Comment by maxogden** [comment]
nice. what else does this need beyond what you have now?

**Comment by jenslind** [comment]
Some input, I'm not too familiar with `codesign`. Also wondering if there should be a verification of the sign afterwards but i guess its not needed because it should throw an error if it fails anyway.

But yeah, what's in the commit works.

**Comment by maxogden** [comment]
gonna merge for now

**Comment by maxogden** [comment]
published as 4.1.0

**Pull request merged**
